# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boosters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('oldScore', models.IntegerField(max_length=4)),
                ('newScore', models.IntegerField(max_length=4)),
                ('email', models.EmailField(blank=True, default='', max_length=30)),
                ('discord', models.CharField(blank=True, default='', max_length=30)),
                ('skype', models.CharField(blank=True, default='', max_length=30)),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('contact', models.CharField(default='', max_length=150)),
                ('price', models.FloatField(max_length=3)),
                ('paid', models.BooleanField(default=True)),
                ('done', models.BooleanField(default=False)),
                ('booster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overwatch.Boosters')),
            ],
            options={
                'verbose_name': 'Оплаченный заказ',
                'verbose_name_plural': 'оплаченные заказы',
            },
        ),
    ]
