# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='booster',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='overwatch.Boosters'),
        ),
        migrations.AlterField(
            model_name='order',
            name='newScore',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='oldScore',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(blank=True, max_length=3),
        ),
    ]
