# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0002_auto_20180505_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
