# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0003_auto_20180505_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='booster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overwatch.Boosters'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='discord',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='newScore',
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name='order',
            name='oldScore',
            field=models.IntegerField(default=1499),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='skype',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
