# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0004_auto_20180505_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Пакет услуг',
                'verbose_name_plural': 'Пакеты услуг',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ на буст', 'verbose_name_plural': 'Заказы на буст'},
        ),
        migrations.AlterField(
            model_name='order',
            name='booster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overwatch.Booster'),
        ),
        migrations.AlterField(
            model_name='order',
            name='newScore',
            field=models.IntegerField(blank=True, default=1500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='oldScore',
            field=models.IntegerField(blank=True, default=1499, null=True),
        ),
        migrations.DeleteModel(
            name='Boosters',
        ),
    ]
