# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0005_auto_20180505_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='pack',
            name='type',
            field=models.CharField(choices=[('B', 'boost'), ('Q', 'qualification')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
