# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0006_auto_20180505_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
