# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0009_order_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='booster',
            field=models.ForeignKey(default='Vova', on_delete=django.db.models.deletion.CASCADE, to='overwatch.Booster'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('B', 'boost'), ('Q', 'qualification')], default='B', max_length=1),
        ),
    ]
