# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0010_auto_20180506_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('B', 'boost'), ('Q', 'qualification')], max_length=1),
        ),
    ]
