# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0011_auto_20180506_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='booster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='overwatch.Booster'),
        ),
    ]
