# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0012_auto_20180506_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='newScore',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='oldScore',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pack',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
