# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0013_auto_20180507_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('B', 'boost'), ('Q', 'qualification'), ('C', 'custom')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pack',
            name='type',
            field=models.CharField(choices=[('B', 'boost'), ('Q', 'qualification'), ('C', 'custom')], max_length=1),
        ),
    ]
